[workspace]
members = [
    "libs/core",
    "libs/parse",
    "libs/graphics",
    "libs/fonts",
    "libs/render",
    "libs/svg",
    "libs/utils",
    "libs/grid",
    "libs/score",
    "libs/gui",
]
