pub const SPACE: f32 = 8.0;
pub const SPACE2: f32 = SPACE * 2.0;
pub const SPACE_HALF: f32 = SPACE / 2.0;
pub const HEAD_WIDTH_BLACK: f32 = SPACE;
pub const HEAD_WIDTH_WHITE: f32 = SPACE * 1.1;
pub const HEAD_WIDTH_WHOLE: f32 = SPACE * 1.3;
pub const REST_WIDTH: f32 = SPACE;
pub const ACCIDENTAL_HEIGHT: f32 = SPACE * 1.2;
pub const ACCIDENTAL_WIDTH: f32 = SPACE * 0.8;
